# Generated by Django 4.2.3 on 2023-07-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Thank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=127)),
                ("description", models.CharField(max_length=511)),
                ("publish_permission", models.BooleanField(default=False)),
                ("image", models.ImageField(upload_to="")),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Draft"),
                            (1, "Sent"),
                            (2, "Delivered"),
                            (3, "Read"),
                            (4, "Answered"),
                            (5, "Published"),
                        ],
                        default=0,
                    ),
                ),
            ],
        ),
    ]
